version: 0.2

phases:
  pre_build:
    commands:
      - echo "Running pre-build steps for Product Service Lambda.."
      - mvn clean install
  build:
    commands:
      - echo "Building Product Service Lambda..."
      - mvn package
  post_build:
    commands:
      - echo "Build completed for Product Service Lambda."
      - mkdir -p target/deployment
      - cp target/*lambda-package.zip target/deployment/

artifacts:
  files:
    - target/deployment/*lambda-package.zip